openapi: 3.1.0
info:
  title: LuzIA API
  version: 1.0.0
  description: API de suporte emocional com frases terapêuticas e ativação de skills por gatilho emocional.
servers:
  - url: https://raw.githubusercontent.com/Luzia1975/Luzia1975/main
paths:
  /skills:
    get:
      operationId: getAllSkills
      summary: Lista todas as skills disponíveis
      responses:
        "200":
          description: Lista de todas as skills
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'
    post:
      operationId: createSkill
      summary: Cria uma nova skill
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Skill'
      responses:
        "201":
          description: Skill criada com sucesso

  /skills/filter:
    get:
      operationId: getSkillsByTrigger
      summary: Lista skills filtradas por gatilho emocional
      parameters:
        - name: trigger
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Lista de skills com gatilho correspondente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Skill'

  /phrases:
    get:
      operationId: getSupportivePhrases
      summary: Retorna frases terapêuticas categorizadas
      responses:
        "200":
          description: Frases por categoria emocional
          content:
            application/json:
              schema:
                type: object
                properties:
                  escuta_ativa_pura:
                    type: array
                    items: { type: string }
                  desistência_cansaço:
                    type: array
                    items: { type: string }
                  autoimagem_abalada:
                    type: array
                    items: { type: string }

  /intro:
    get:
      operationId: getIntroduction
      summary: Mensagem inicial da L.U.Z.I.A.
      responses:
        "200":
          description: Mensagem de boas-vindas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    Skill:
      type: object
      required:
        - name
        - description
        - triggers
      properties:
        name:
          type: string
        description:
          type: string
        triggers:
          type: array
          items:
            type: string
